-- MySQL Script generated by MySQL Workbench
-- jue 14 nov 2022 08:44:20 CST
-- Model: New Model    Version: 1.0 
-- MySQL Workbench Forward Engineering 

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Banco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Banco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Banco` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `Banco` ;

-- -----------------------------------------------------
-- Table `Banco`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Banco`.`Usuarios` (
  `idUsuario` INT NOT NULL,
  `Email` VARCHAR(255) NULL,
  `Password` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `Banco`.`Cuentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Banco`.`Cuentas` (
  `idCuenta` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `Monto` DECIMAL(10,6) NULL,
  PRIMARY KEY (`idCuenta`),
  INDEX `fk_Cuentas_Usuarios_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Cuentas_Usuarios`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `Banco`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `Banco`.`Transacciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Banco`.`Transacciones` (
  `idTransaccion` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `Monto` DECIMAL(4,2) UNSIGNED NOT NULL,
  `Concepto` TEXT(200) NOT NULL,
  PRIMARY KEY (`idTransaccion`),
  INDEX `fk_Transacciones_Usuarios_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Transacciones_Usuarios`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `Banco`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'usuario' IDENTIFIED BY 'oracle';

GRANT ALL ON `Banco`.* TO 'usuario';
GRANT SELECT, INSERT, TRIGGER ON TABLE `Banco`.* TO 'usuario';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `Banco`.* TO 'usuario';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
